security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/exchange/admin, roles: ROLE_ADMIN }
        - { path: ^/exchange/step, roles: ROLE_USER }
        - { path: ^/exchange$, roles: IS_AUTHENTICATED_ANONYMOUSLY }