# config/services.yaml
parameters: ~

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # ============================
    # ADMIN CONTROLLERS
    # ============================
    App\Controller\Admin\:
        resource: '../src/Controller/Admin/'
        tags: ['controller.service_arguments']

    # ============================
    # USER CONTROLLERS
    # ============================
    App\Controller\User\:
        resource: '../src/Controller/User/'
        tags: ['controller.service_arguments']

    # ============================
    # LOGIN SUCCESS HANDLER
    # ============================
    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'

    # ============================
    # GENERAL APP SERVICES
    # ============================
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Controller/Admin/'
            - '../src/Controller/User/'
